To add the name of the file being processed in the log output, you can modify the `Process each YAML file` step to include the filename in the `rmoa lint` command. Here's the updated `zuplo-integration.yml`:

```yaml
name: Rate my OAS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio
      - uses: actions/checkout@v4

      # Paso 2: Validar que cada archivo tenga la versión de OpenAPI
      - name: Validate OpenAPI version in YAML files
        run: |
          for file in ./apis/*.yaml; do
            if ! grep -q "openapi:" "$file"; then
              echo "ERROR: $file is missing 'openapi' version. Please specify a valid OpenAPI version (e.g., 3.0.2)."
              exit 1
            fi
          done

      # Paso 3: Instalar la versión requerida de Node.js (20.0.0 o superior)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Paso 4: Instalar RMOA
      - name: Install RMOA
        run: npm install -g rmoa

      # Paso 5: Iterar sobre cada archivo YAML en el directorio apis
      - name: Process each YAML file
        run: |
          for file in ./apis/*.yaml; do
            echo "Processing $file..."
            rmoa lint \
              --api-key zpka_3857be3f8c414be1a68a23304c863a94_4c9a8d1e \
              --filename "$file" \
              --minimum-score 70 \
              --max-errors 0 \
              --max-warnings 200
              echo "Finished processing $file."
          done
```
