name: Rate my OAS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del repositorio
      - uses: actions/checkout@v4

      # Paso 2: Debug para listar archivos en la carpeta apis
      - name: Debug - List files in apis directory
        run: ls -l ./apis

      # Paso 3: Instalar la versión requerida de Node.js (20.0.0 o superior)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Instala la última versión compatible de Node.js 20.x

      # Paso 4: Instalar RMOA
      - name: Install RMOA
        run: npm install -g rmoa

      # Paso 5: Ejecutar RMOA action para analizar el archivo OpenAPI
      - uses: zuplo/rmoa-action@v1
        with:
          filepath: 'apis/vehicle_images_api.yaml' # Cambia si deseas analizar otro archivo
          apikey: zpka_3857be3f8c414be1a68a23304c863a94_4c9a8d1e

      # Paso 6: Usar RMOA CLI para análisis adicional
      - name: Run RMOA lint
        run: rmoa lint --api-key zpka_3857be3f8c414be1a68a23304c863a94_4c9a8d1e --filename apis/vehicle_images_api.yaml
