name: Rate my OAS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  rate-my-open-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zuplo/rmoa-action@v1
        with:
          filepath: 'apis/*.yaml'
          apikey: zpka_3857be3f8c414be1a68a23304c863a94_4c9a8d1e
      - name: Rate My Open API
        run: rmoa lint

 
